version: '3.9'
services:
  postgres-resource:
    image: postgres:16
    container_name: postgres-resource
    environment:
      POSTGRES_DB: resource
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  postgres-metadata:
    image: postgres:16
    container_name: postgres-metadata
    environment:
      POSTGRES_DB: metadata
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data