version: '3.9'
services:
  postgres-resource-service-db:
    image: postgres:16
    container_name: postgres-resource
    environment:
      POSTGRES_DB: resource_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  postgres-song-service-db:
    image: postgres:16
    container_name: postgres-metadata
    environment:
      POSTGRES_DB: song_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"