version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: resource
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: